name: nba-agent-backend-env
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - blas=1.0=mkl
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - click=8.1.8
  - colorama=0.4.6
  - expat=2.7.1
  - fastapi=0.112.2
  - freeglut=3.4.0
  - freetype=2.13.3
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.1
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.2
  - pytz=2024.1
  - setuptools=78.1.1
  - six=1.17.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tbb=2021.8.0
  - tk=8.6.14
  - typing-extensions=4.12.2
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - matplotlib==3.10.3
      - agno==1.4.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - attrs==25.3.0
      - black==25.1.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - coverage==7.8.0
      - frozenlist==1.6.0
      - grpcio==1.60.1
      - h11==0.16.0
      - httpcore==1.0.9
      - importlib-metadata==8.4.0
      - iniconfig==2.1.0
      - isort==6.0.1
      - jiter==0.9.0
      - multidict==6.4.3
      - mypy==1.15.0
      - nba-api==1.9.0
      - numpy==1.26.4
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - packaging==24.2
      - pathspec==0.12.1
      - propcache==0.3.1
      - protobuf==4.25.7
      - pydantic-settings==2.9.1
      - pytest==8.3.5
      - pytest-asyncio==0.26.0
      - pytest-cov==6.1.1
      - regex==2024.11.6
      - sqlalchemy==2.0.35
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - watchfiles==1.0.5
      - websockets==15.0.1
      - yarl==1.20.0
      - zipp==3.21.0
