"use client";

import { useEffect, useRef, useState } from "react";
import type { ActivityRecord } from "../lib/chat";

type View={label:string;meta:string;fields:[string,string][]};
const words=(v:unknown)=>String(v??"").replace(/_/g," ");
const amount=(v:unknown,n:string)=>`${Number(v)||0} ${n}${Number(v)===1?"":"s"}`;
const payload=(i:ActivityRecord)=>i.data.data&&typeof i.data.data==="object"&&!Array.isArray(i.data.data)?i.data.data as Record<string,unknown>:{};
function describe(i:ActivityRecord):View{const d=payload(i),name=words(d.name||d.capability||"data");
 if(i.kind==="stage_summary")return{label:"Mapped the question",meta:amount(d.requirement_count,"requirement"),fields:[["Mode",words(d.mode)],["Season",words(d.season||"Current")],["Entities",String(d.entity_count??0)]]};
 if(i.kind==="plan_update")return{label:"Planned the research",meta:amount(d.node_count,"step"),fields:[["Tools",Array.isArray(d.capabilities)?d.capabilities.map(words).join(", "):"None"],["Unknown",String(d.unknown_capability_count??0)]]};
 if(i.kind==="tool_call")return{label:`Searching ${name}`,meta:"Running",fields:[["Inputs",amount(d.argument_count,"field")],["Unrecognized",String(d.unknown_argument_count??0)]]};
 if(i.kind==="tool_result"){const bad=i.transition==="failed"||i.status==="fail"||i.status==="failed";return{label:bad?`${name} unavailable`:`Found ${name}`,meta:bad?"Failed":d.rows==null?"Complete":amount(d.rows,"row"),fields:[["Status",bad?"Failed":"Complete"],...(d.rows==null?[]:[["Rows",String(d.rows)] as [string,string]])]};}
 if(i.kind==="evidence_update"){const ok=i.transition==="admitted";return{label:ok?`Qualified ${name}`:`Set aside ${name}`,meta:ok?amount(d.rows,"row"):"Rejected",fields:[["Coverage",words(d.coverage)],["Quality",words(d.qualification)],["Warnings",String(d.warning_count??0)],["Source date",words(d.as_of||"Not supplied")]]};}
 if(i.kind==="verification_update")return{label:`Verified ${Number(d.supported_count)||0} of ${Number(d.claim_count)||0} claims`,meta:Number(d.missing_count)||Number(d.contradiction_count)?amount(d.missing_count,"gap"):"Passed",fields:[["Round",words(d.round)],["Repairs",String(d.repair_count??0)]]};
 return{label:i.title,meta:i.summary||"",fields:[]};}
function Mark({item,active}:{item:ActivityRecord;active:boolean}){const bad=item.transition==="failed"||item.status==="fail"||item.status==="failed";return <span aria-hidden style={{width:15,display:"inline-grid",placeItems:"center",color:bad?"var(--color-ember)":"var(--color-ash-gray)"}}>{active?<span className="activity-orbit"/>:bad?"!":item.kind==="verification_update"||item.kind==="evidence_update"?"✓":item.kind==="tool_call"||item.kind==="tool_result"?"⌕":"·"}</span>}
function Step({item,active,index}:{item:ActivityRecord;active:boolean;index:number}){const [open,setOpen]=useState(false),[tech,setTech]=useState(false),v=describe(item);return <div className="activity-step" style={{animationDelay:`${Math.min(index,8)*36}ms`}}>
 <button type="button" onClick={()=>setOpen(x=>!x)} aria-expanded={open} style={{width:"100%",display:"grid",gridTemplateColumns:"18px minmax(0,1fr) auto",gap:8,alignItems:"center",padding:"5px 0",border:0,background:"none",textAlign:"left",cursor:"pointer"}}><Mark item={item} active={active}/><span style={{fontSize:12.5,color:"var(--color-ink-black)",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{v.label}</span><span className={active?"activity-shimmer":""} style={{padding:"3px 7px",borderRadius:6,background:"var(--color-stone-canvas)",fontSize:10.5,color:"var(--color-ash-gray)",whiteSpace:"nowrap"}}>{v.meta}</span></button>
 {open&&<div className="activity-detail" style={{margin:"3px 0 7px 26px",padding:"9px 10px",borderRadius:8,background:"var(--color-stone-canvas)"}}><dl style={{display:"flex",gap:7,flexWrap:"wrap",margin:0}}>{v.fields.map(([k,x])=><div key={k} style={{display:"inline-flex",gap:5,padding:"4px 7px",borderRadius:6,border:"1px solid var(--color-stone-border)",fontSize:10.5}}><dt style={{color:"var(--color-ash-gray)"}}>{k}</dt><dd style={{margin:0,color:"var(--color-warm-gray)"}}>{x}</dd></div>)}</dl><button type="button" onClick={()=>setTech(x=>!x)} style={{marginTop:8,padding:0,border:0,background:"none",fontSize:10,color:"var(--color-ash-gray)",cursor:"pointer"}}>{tech?"Hide technical data":"Technical data"}</button>{tech&&<pre style={{margin:"7px 0 0",padding:8,maxHeight:180,overflow:"auto",whiteSpace:"pre-wrap",overflowWrap:"anywhere",borderRadius:6,background:"var(--color-paper-white)",fontSize:9.5,lineHeight:1.45,color:"var(--color-warm-gray)"}}>{JSON.stringify(item.data,null,2)}</pre>}</div>}
 </div>}
export default function ActivityTimeline({items,running}:{items:ActivityRecord[];running:boolean}){const [open,setOpen]=useState(true),box=useRef<HTMLDivElement>(null);useEffect(()=>{if(open&&box.current)box.current.scrollTo({top:box.current.scrollHeight,behavior:"smooth"})},[items.length,open]);const tools=items.filter(i=>i.kind==="tool_call").length,evidence=items.filter(i=>i.kind==="evidence_update"&&i.transition==="admitted").length;const completed=!running&&items.length>0;return <>
 <style jsx global>{`@keyframes activity-in{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}@keyframes activity-orbit{to{transform:rotate(360deg)}}@keyframes activity-shimmer{0%,100%{opacity:.48}50%{opacity:1}}.activity-step{opacity:0;animation:activity-in .28s cubic-bezier(.2,.8,.2,1) forwards}.activity-detail{animation:activity-in .18s ease-out}.activity-orbit{width:10px;height:10px;border-radius:50%;border:1.5px solid var(--color-stone-border);border-top-color:var(--color-cyan-signal);animation:activity-orbit .8s linear infinite}.activity-shimmer{animation:activity-shimmer 1.35s ease-in-out infinite}.activity-timeline{position:relative;padding-top:3px}.activity-progress-rail{position:absolute;top:0;left:0;width:100%;height:2px;overflow:hidden;border-radius:999px;background:var(--color-stone-border)}.activity-progress-rail::after{content:"";position:absolute;inset:0;width:34%;border-radius:inherit;background:var(--color-cyan-signal);opacity:0;transform:translateX(-110%)}.activity-timeline.is-running .activity-progress-rail::after{opacity:1;animation:activity-progress 1.2s cubic-bezier(.4,0,.2,1) infinite}.activity-timeline.is-complete .activity-progress-rail::after{width:100%;opacity:.55;transform:none;transition:width .28s cubic-bezier(.16,1,.3,1),opacity .2s ease}@keyframes activity-progress{to{transform:translateX(395%)}}@media(prefers-reduced-motion:reduce){.activity-step,.activity-detail,.activity-orbit,.activity-shimmer,.activity-progress-rail::after{animation:none!important;transition:none!important;opacity:1!important}.activity-timeline.is-running .activity-progress-rail::after{width:42%;transform:none}}`}</style>
 <div className={`activity-timeline ${running?"is-running":completed?"is-complete":""}`}><span className="activity-progress-rail" aria-hidden="true"/><button type="button" onClick={()=>setOpen(x=>!x)} aria-expanded={open} style={{display:"inline-flex",alignItems:"center",gap:7,padding:"5px 9px",border:0,borderRadius:7,background:"var(--color-stone-canvas)",color:"var(--color-warm-gray)",fontSize:11.5,cursor:"pointer"}}><span style={{transform:open?"rotate(90deg)":"none",transition:"transform .16s"}}>›</span>{running?"Working":`${tools} tool call${tools===1?"":"s"}`}{!running&&evidence>0?`, ${evidence} evidence set${evidence===1?"":"s"}`:""}</button>
 {open&&<div ref={box} role="log" aria-live="polite" aria-label="Live analysis activity" style={{marginTop:8,maxHeight:390,overflowY:"auto",padding:"0 2px 2px 7px",borderLeft:"1px solid var(--color-stone-border)"}}>{items.map((i,n)=><Step key={i.eventId} item={i} index={n} active={running&&n===items.length-1}/>)}</div>}</div></>}
