"""Structural checks on the season_consistency scored-output mirror.

The scorer itself lives in dime-internal/evals/dimebench (dime/ stays
code-only); this fixture mirrors its behavior/verdicts in dime so
Instinct QA can verify scoring without repo access. Expected values are
generated by running the canonical scorer, not hand-typed - so this test
only checks the fixture's shape and internal consistency, never re-derives
scores. Hermetic: stdlib only.
"""

import json
from pathlib import Path

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "season_consistency_mirror.json"


def _load():
    data = json.loads(FIXTURE.read_text())
    assert "header" in data and "cases" in data
    return data


def test_fixture_has_source_attribution():
    data = _load()
    header = data["header"]
    assert "dime-internal" in header["canonical_source"]
    assert header["canonical_sha"]
    assert header["generated"]
    assert any("2024-25" in r for r in header["rules"])


def test_cases_well_formed():
    data = _load()
    ids = [c["id"] for c in data["cases"]]
    assert len(ids) == len(set(ids)) and len(ids) >= 10
    for c in data["cases"]:
        assert c["metric"] in ("season_consistency", "numeric_acc")
        assert isinstance(c["facts"], dict)
        assert isinstance(c["answer"], str) and c["answer"]
        assert isinstance(c["expected"], (int, float))


def test_wrong_season_verdicts_are_zero():
    data = _load()
    by_id = {c["id"]: c for c in data["cases"]}
    assert by_id["numeric_wrong_season_number"]["expected"] == 0.0
    assert by_id["numeric_right_number_wrong_season_phrasing"]["expected"] == 0.0
    assert by_id["consistency_wrong_season"]["expected"] == 0.0


def test_no_penalty_without_season_claim():
    data = _load()
    by_id = {c["id"]: c for c in data["cases"]}
    assert by_id["consistency_no_mention"]["expected"] == 1.0
    assert by_id["numeric_no_season_mention"]["expected"] == 1.0
    assert by_id["consistency_no_season_label"]["expected"] == 1.0
