name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: backend/environment.yml
          activate-environment: nba-agent-env  # Change if your env name is different
          auto-activate-base: false

      - name: Show conda info
        run: conda info

      - name: Run pytest
        shell: bash -l {0}
        run: |
          conda activate nba-agent-env
          pytest backend/smoke_tests --maxfail=3 --disable-warnings -v

      - name: Deploy (placeholder)
        if: success()
        run: echo "Deploy step goes here (e.g., Docker build/push, SSH, or cloud deploy)" 